/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Admin = IDL.Record({
  'principal' : IDL.Principal,
  'email' : IDL.Text,
});
export const Submission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAdmin' : IDL.Func([IDL.Text], [], []),
  'getAllAdmins' : IDL.Func([], [IDL.Vec(Admin)], ['query']),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeAdmin' : IDL.Func([], [], []),
  'submitForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateAdminEmail' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Admin = IDL.Record({ 'principal' : IDL.Principal, 'email' : IDL.Text });
  const Submission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'addAdmin' : IDL.Func([IDL.Text], [], []),
    'getAllAdmins' : IDL.Func([], [IDL.Vec(Admin)], ['query']),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeAdmin' : IDL.Func([], [], []),
    'submitForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateAdminEmail' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };